Title: 95740 – gdesklets broken on amd64 because architecture lacks fast mutexes
URL: https://bugs.gentoo.org/show_bug.cgi?id=95740

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 95740
gdesklets broken on amd64 because architecture lacks fast mutexes
Last modified: 2005-09-02 13:20:37 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 95740 
      - gdesklets broken on amd64 because architecture lacks fast mutexes


Summary:
gdesklets broken on amd64 because architecture lacks fast mutexes
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

AMD64
        Linux
      







Importance:
      
High
       normal
      


Assignee:

AMD64 Project








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2005-06-10 21:05 UTC by Mark Duckworth





      Modified:
    
2005-09-02 13:20 UTC
      (History)
    




          CC List:
        

2 
          users
          
            (show)
          



gdesklets
gnome









See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Mark Duckworth





          2005-06-10 21:05:02 UTC
        

I've given it a lot of time and the problem hasn't been fixed, nor have there
been any other bug reports about it.  I'm a little confused here, but any
remotely new version of gdesklets (like > .33) don't work on my AMD64 machine. 
I have a 32bit P4 at work which it works fine on.  This is what it looks like
when starting gdesklets.

Starting gdesklets-daemon...
Connecting to daemon [     ###     ]

It will sit like this FOREVER.  If I let it go it will time out.  If I ctrl-c
it, it will say:

Starting gdesklets-daemon...
Connecting to daemon [   ###       ]Error while starting gdesklets-daemon
More information about this crash is available in
"/home/mduckworth/.gdesklets/logs/gdesklets%3A0.0.log".

Ok:
mduckworth@evil ~ $ cat /home/mduckworth/.gdesklets/logs/gdesklets%3A0.0.log
Log messages of /home/mduckworth/.gdesklets/logs/gdesklets%3A0.0.log

==========================================================[06/11/05-00:01:48]======
Error in the core! Please report this bug!

[EXC]bsddb._db.DBInvalidArgError:
[EXC](22, 'Invalid argument -- architecture lacks fast mutexes: applications
cannot be threaded')
in /usr/lib/gdesklets/gdesklets-daemon: line 127 ?
in /usr/lib/gdesklets/gdesklets-daemon: line 114 _gdesklets_main
in /usr/lib/gdesklets/utils/ErrorFormatter.py: line 119 _new_imp
in /usr/lib/gdesklets/main/Starter.py: line 2 ?
in /usr/lib/gdesklets/utils/ErrorFormatter.py: line 119 _new_imp
in /usr/lib/gdesklets/config/DaemonConfigger.py: line 1 ?
in /usr/lib/gdesklets/utils/ErrorFormatter.py: line 119 _new_imp
in /usr/lib/gdesklets/config/StateSaver.py: line 113 ?
in /usr/lib/gdesklets/config/StateSaver.py: line 27 __init__
in /usr/lib/python2.4/shelve.py: line 231 open
in /usr/lib/python2.4/shelve.py: line 212 __init__
in /usr/lib/python2.4/anydbm.py: line 83 open
in /usr/lib/python2.4/dbhash.py: line 16 open
in /usr/lib/python2.4/bsddb/__init__.py: line 285 hashopen
in /usr/lib/python2.4/bsddb/__init__.py: line 339 _openDBEnv
[---]/usr/lib/python2.4/bsddb/__init__.py
[---]  334
[---]  335 #----------------------------------------------------------------------
[---]  336
[---]  337 def _openDBEnv():
[---]  338     e = db.DBEnv()
[ERR]> 339     e.open('.', db.DB_PRIVATE | db.DB_CREATE | db.DB_THREAD |
db.DB_INIT_LOCK | db.DB_INIT_MPOOL)
[---]  340     return e
[---]  341
[---]  342 def _checkflag(flag, file):
[---]  343     if flag == 'r':
[---]  344         flags = db.DB_RDONLY
[---]  345     elif flag == 'rw':


Exception exceptions.AttributeError: "DbfilenameShelf instance has no attribute
'writeback'" in mduckworth@evil ~ $

So I've tried to recompile python without berkeley DB support to no avail, I've
tried to delete all my gdesklets preferences out of ~/.gdesklets as well as
gconf.  I've tried just about everything.  If I use the old version of
gdesklets, I can't use starterbar which I love.

Reproducible: Always
Steps to Reproduce:
1. gdesklets start
2. 
3.




Output of emerge info
Portage 2.0.51.22-r1 (default-linux/amd64/2005.0, gcc-3.4.4, glibc-2.3.5-r0,
2.6.11-gentoo-r9 x86_64)
=================================================================
System uname: 2.6.11-gentoo-r9 x86_64 AMD Athlon(tm) 64 Processor 3000+
Gentoo Base System version 1.6.12
distcc 2.18.3 x86_64-pc-linux-gnu (protocols 1 and 2) (default port 3632) [disabled]
dev-lang/python:     2.3.5, 2.4.1
sys-apps/sandbox:    1.2.9
sys-devel/autoconf:  2.13, 2.59-r6
sys-devel/automake:  1.4_p6, 1.5, 1.6.3, 1.7.9-r1, 1.8.5-r3, 1.9.5
sys-devel/binutils:  2.16-r1
sys-devel/libtool:   1.5.18
virtual/os-headers:  2.6.11-r1
ACCEPT_KEYWORDS="amd64 ~amd64"
AUTOCLEAN="yes"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=athlon64 -O2 -pipe -fomit-frame-pointer -frename-registers
-fPIC"CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/kde/2/share/config /usr/kde/3.3/env
/usr/kde/3.3/share/config /usr/kde/3.3/shutdown /usr/kde/3.4/env
/usr/kde/3.4/share/config /usr/kde/3.4/shutdown /usr/kde/3/share/config
/usr/lib/X11/xkb /usr/lib/mozilla/defaults/pref /usr/share/config
/var/qmail/control"
CONFIG_PROTECT_MASK="/etc/gconf /etc/terminfo /etc/texmf/web2c /etc/env.d"
CXXFLAGS="-march=athlon64 -O2 -pipe -fomit-frame-pointer -frename-registers -fPIC"
DISTDIR="/usr/portage/distfiles"
FEATURES="autoconfig distlocks sandbox sfperms strict"
GENTOO_MIRRORS="http://gentoo.mirrors.pair.com"
MAKEOPTS="-j2"
PKGDIR="/usr/portage/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
PORTDIR_OVERLAY="/usr/local/portage"
SYNC="rsync://rsync.gentoo.org/gentoo-portage"
USE="X aalib acpi adns alsa amd64 arts berkdb bitmap-fonts bonobo cdr crypt cups
curl dga dv dvd dvdread eds encode esd fam fame fbcon flac font-server fortran
gd gdbm gif gnome gpm gstreamer gtk gtk2 gtkhtml guile icu imagemagick imlib
ipv6 jack java jp2 jpeg jpg junit lame ldap libwww lirc lzw lzw-tiff mad mikmod
mjpeg motif mozilla mp3 mpeg mysql ncurses nls odbc ogg oggvorbis opengl oss pam
perl png print python qt readline samba sasl sdl slang splash ssl svg tcltk tcpd
tetex theora tiff truetype truetype-fonts type1-fonts usb userlocales vorbis
xine xinerama xml xml2 xmms xpm xrandr xv zlib userland_GNU kernel_linux
elibc_glibc"
Unset:  ASFLAGS, CTARGET, LANG, LC_ALL, LDFLAGS, LINGUAS




Comment 1


Mike Doty (RETIRED)






          2005-06-10 21:10:29 UTC
        

mike@koala:~> zgrep FUTEX /proc/config.gz
CONFIG_FUTEX=y


is this what you're refering to?




Comment 2


Mark Duckworth





          2005-06-10 21:40:00 UTC
        

I dunno.  I don't know what Fast mutexes are.  All I know is the output.  Mine
is set the same as yours:

$ zgrep FUTEX /proc/config.gz
CONFIG_FUTEX=y

Anyway, I did figure out a way to sneak around it.  I moved the bsddb folder
under the python2.4 site files elsewhere which got it to startup.  It complains
about not having the proper db support when it tries to run the desklet manager
thing but if you open desklets manually using the console, they all work.  Rock.
 All I care about is "mostly working"  But this still is an issue?




Comment 3


Olivier Crete (RETIRED)






          2005-06-11 01:08:29 UTC
        

which version of python did you use to launch gdesklets... the fact that you
have both 2.3 and 2.4 might confuse something.. because futexes are available on
amd64...




Comment 4


Simon Stelling (RETIRED)






          2005-09-02 13:20:37 UTC
        

probably the different python versions are the problem, as Tester stated in
Comment #3.. Closing, please reopen if it still doesnt' work for you









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

