Title: 287751 – app-pda/msynctool-0.36 ImportError: No module named opensync
URL: https://bugs.gentoo.org/show_bug.cgi?id=287751

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 287751
app-pda/msynctool-0.36 ImportError: No module named opensync
Last modified: 2011-03-13 18:56:02 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 287751 
      - app-pda/msynctool-0.36 ImportError: No module named opensync


Summary:
app-pda/msynctool-0.36 ImportError: No module named opensync
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Ryan Hill (RETIRED)








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:




354423



 

        Show dependency tree





 





      Reported:
    
2009-10-05 12:59 UTC by Juergen Rose





      Modified:
    
2011-03-13 18:56 UTC
      (History)
    




          CC List:
        

2 
          users
          
            (show)
          



pda
rhill









See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Juergen Rose





          2009-10-05 12:59:37 UTC
        

I would like to add a new group to opensync. I get the following result:

rose@lynx:/home/rose(5)$ msynctool --addgroup nokia_e71
rose@lynx:/home/rose(6)$ msynctool --addmember nokia_e71 syncml-obex-client
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
ImportError: No module named opensync
rose@lynx:/home/rose(7)$ echo $?
0
rose@lynx:/home/rose(9)$ msynctool --addmember nokia_e71 evo2-sync
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
ImportError: No module named opensync
rose@lynx:/home/rose(10)$ msynctool --configure nokia_e71 1
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
ImportError: No module named opensync
rose@lynx:/home/rose(11)$ msynctool --configure nokia_e71 2
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
ImportError: No module named opensync
rose@lynx:/home/rose(14)$ multisyncgui 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
ImportError: No module named opensync


rose@lynx:/home/rose(60)$ msynctool --discover nokia_e71 1
   same errors
Discovered Objtypes:
        contact
                Format: vcard21
                                 conversion config: (null)
        event
                Format: vevent20
                                 conversion config: (null)
rose@lynx:/home/rose(61)$ msynctool --discover nokia_e71 2
   same errors
Discovered Objtypes:
        contact
                Format: vcard30
                                 conversion config: VCARD_EXTENSION=Evolution
                Format: vcard21
                                 conversion config: VCARD_EXTENSION=Evolution
        event
                Format: vevent20
                                 conversion config: (null)
        note
                Format: vjournal
                                 conversion config: (null)
        todo
                Format: vtodo20
                                 conversion config: (null)

rose@lynx:/home/rose(62)$ msynctool --sync nokia_e71
   same errors
   The nokia ask me for a password, I enter the same number, I entered while 'msynctool --configure nokia_e71  1'

The terminal window of the PC shows
(process:2206): GLib-GObject-CRITICAL **: gtype.c:2458: initialization assertion failed, use IA__g_type_init() prior to this function

(process:2206): GLib-GObject-CRITICAL **: g_object_new: assertion `G_TYPE_IS_OBJECT (object_type)' failed

(process:2206): GLib-GObject-CRITICAL **: g_object_ref: assertion `G_IS_OBJECT (object)' failed
contact sink of member 2 of type evo2-sync had an error: Broken Pipe
event sink of member 2 of type evo2-sync had an error: Broken Pipe
Main sink of member 2 of type evo2-sync had an error: Broken Pipe
contact sink of member 1 of type syncml-obex-client just connected
event sink of member 1 of type syncml-obex-client just connected
Main sink of member 1 of type syncml-obex-client had an error: Link Error: 0x0
The sync failed: No objtypes left without error. Aborting
Main sink of member 2 of type evo2-sync just disconnected
Main sink of member 1 of type syncml-obex-client just disconnected
�m sink of member 1 of type syncml-obex-client just disconnected
Speicherzugriffsfehler


Any idea?

Reproducible: Always




Comment 1


Juergen Rose





          2009-10-05 16:01:14 UTC
        

After reemerging libopensync-plugin-python I get less error messages, but I still cannot sync my cellphone with evolution. I see the following:

rose@lynx:/home/rose(17)$ msynctool --sync nokia_e71 
Synchronizing group "nokia_e71" 
The previous synchronization was unclean. Slow-syncing
contact sink of member 1 of type syncml-obex-client just connected
event sink of member 1 of type syncml-obex-client just connected
contact sink of member 2 of type evo2-sync just connected
event sink of member 2 of type evo2-sync just connected
Main sink of member 2 of type evo2-sync just connected

At this point the cellphone ask for a password, even if did not enter
a password during "msynctool --configure nokia_e71 1". If I cancel or enter the password from "msynctool --configure nokia_e71 1", I get then:

Main sink of member 1 of type syncml-obex-client had an error: Link Error: 0x0
The sync failed: At least one objenit hat problems while connecting. Aborting
Main sink of member 1 of type syncml-obex-client just disconnected
contact sink of member 1 of type syncml-obex-client just disconnected
event sink of member 1 of type syncml-obex-client just disconnected
contact sink of member 2 of type evo2-sync just disconnected
event sink of member 2 of type evo2-sync just disconnected
Main sink of member 2 of type evo2-sync just disconnected
All clients have disconnected
ERROR: At least one objenit hat problems while connecting. Aborting





Comment 2


Thilo Bangert (RETIRED) (RETIRED)






          2010-05-26 12:13:47 UTC
        

can you try osynctool-0.39 (msynctool changed name with opensync 0.38)






Comment 3


Juergen Rose





          2010-05-27 16:05:58 UTC
        

If I try osynctool from app-pda/osynctool-0.39 I get the following:

rose@lynx:/home/rose(1)$ osynctool --sync nokia_e71 
Synchronizing group "nokia_e71" 
The previous synchronization was unclean. Slow-syncing
/home/rose/.opensync/group3/2/evo2-sync.conf:3: element address_path: Schemas validity error : Element 'address_path': This element is not expected. Expected is one of ( AdvancedOptions, Authentication, Connection, Localization, Resources ).
ERROR: Plugin configuration file is not valid! /usr/share/libopensync1/schemas/plugin_config.xsd


rose@lynx:/home/rose(3)$ cat /home/rose/.opensync/group3/2/evo2-sync.conf
<?xml version="1.0"?>
<config>
  <address_path>default</address_path>
  <calendar_path>default</calendar_path>
  <memos_path>default</memos_path>
  <tasks_path>default</tasks_path>
</config>

It seems that osynctool does not like my old config. Are there any howtos for the generation of the config files?





Comment 4


Thilo Bangert (RETIRED) (RETIRED)






          2010-05-27 18:09:28 UTC
        

are all your plugins of version 0.39?

unfortunately docs for opensync are sparse. please check opensync.org...





Comment 5


Ryan Hill (RETIRED)






          2011-03-13 18:56:02 UTC
        

the original bug should be taken care of now since the python stuff has been fixed.  the rest seems to be the result of using 0.39 plugins with msynctool or improper configuration.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

