Title: 727128 – x11-drivers/nvidia-drivers-440.82-r3 - doman: nvidia-cuda-mps-control.1 does not exist
URL: https://bugs.gentoo.org/show_bug.cgi?id=727128

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 727128
x11-drivers/nvidia-drivers-440.82-r3 - doman: nvidia-cuda-mps-control.1 does not exist
Last modified: 2020-06-13 08:46:24 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 727128 
      - x11-drivers/nvidia-drivers-440.82-r3 - doman: nvidia-cuda-mps-control.1 does not exist


Summary:
x11-drivers/nvidia-drivers-440.82-r3 - doman: nvidia-cuda-mps-control.1 does ...
        









Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

AMD64
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Jeroen Roovers (RETIRED)








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2020-06-04 13:08 UTC by Markus Giese





      Modified:
    
2020-06-13 08:46 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:


727126





Package list:







Runtime testing required:

---























      Attachments
    




emerge --info

              (emergeinfo.log,5.84 KB,
                text/plain)

            
2020-06-04 13:09 UTC,

            Markus Giese




Details





build.log

              (build.log,783.45 KB,
                text/plain)

            
2020-06-04 13:14 UTC,

            Markus Giese




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Markus Giese





          2020-06-04 13:08:39 UTC
        

when emerge the mentioned driver, i get several errors regarding missing files.

strange thing is, i could compile this driver fine, some weeks ago

Reproducible: Always

Steps to Reproduce:
1.emerge nvidia-drivers
2.
3.
Actual Results:  
missing files : 

nvidia-cuda-mps-control.1
nvidia-modprobe.1
nvidia-persistened.1
nvidia-settings.1
nvidia-smi-1
nvidia-xconfig.1



Expected Results:  
should extract the files from source, the respective files exist as *.gz file




Comment 1


Markus Giese





          2020-06-04 13:09:05 UTC
        

Created attachment 643412 [details]
emerge --info

emerge --info




Comment 2


Markus Giese





          2020-06-04 13:14:27 UTC
        

Created attachment 643414 [details]
build.log

build.log




Comment 3


Jeroen Roovers (RETIRED)






          2020-06-05 06:24:01 UTC
        

This looks a lot like bug #727126 - could you try if upgrading to (stable) =sys-apps/portage-2.3.99-r2 fixes both bugs you reported?




Comment 4


Jeroen Roovers (RETIRED)






          2020-06-05 06:28:05 UTC
        

Comment on attachment 643414 [details]
build.log

>>>> Preparing source in /var/tmp/portage/x11-drivers/nvidia-drivers-440.82-r3/work ...
>no
>no
>no
>no
>no
>no
>no

No?




Comment 5


Markus Giese





          2020-06-05 19:10:56 UTC
        

thanks for your suggestion, but i am running already :

[ebuild   R    ] sys-apps/portage-2.3.99-r2::gentoo  USE="(ipc) native-extensions rsync-verify xattr -apidoc -build -doc -gentoo-dev (-selinux)" PYTHON_TARGETS="python3_6 (-pypy3) -python3_7 (-python3_8)" 1,028 KiB

thanks anyways




Comment 6


Markus Giese





          2020-06-05 19:11:52 UTC
        

(In reply to Jeroen Roovers from comment #4)
> Comment on attachment 643414 [details]
> build.log
> 
> >>>> Preparing source in /var/tmp/portage/x11-drivers/nvidia-drivers-440.82-r3/work ...
> >no
> >no
> >no
> >no
> >no
> >no
> >no
> 
> No?

yeah, i saw that, but dont know where that comes from,,,




Comment 7


Markus Giese





          2020-06-12 20:51:18 UTC
        

fixed by remerging gzip, somehow my gunzip had been corrupted









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

