Title: 104853 – games-board/pysol-4.82 fails to run with Python 2.4
URL: https://bugs.gentoo.org/show_bug.cgi?id=104853

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 104853
games-board/pysol-4.82 fails to run with Python 2.4
Last modified: 2006-03-24 14:18:56 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 104853 
      - games-board/pysol-4.82 fails to run with Python 2.4


Summary:
games-board/pysol-4.82 fails to run with Python 2.4
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] Games

  (show other bugs)



Hardware:

AMD64
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Games








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2005-09-04 20:20 UTC by Brian Hall





      Modified:
    
2006-03-24 14:18 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Brian Hall





          2005-09-04 20:20:05 UTC
        

THIS IS NOT A DUPLICATE OF BUG # 81176! I tried to reopen it but that was denied
due to insufficient permissions.

When emerging pysol on my ~amd64 box with python 2.4.1, no "pysol_24.pyc" file
is generated in /usr/share/pysol/4.82/ even though the ebuild output says:

 * Cleaning orphaned Python bytecode from /usr/games/lib/pysol ..
>>> original instance of package unmerged safely.
 * Remember, in order to play games, you have to
 * be in the 'games' group.

 * Just run 'gpasswd -a <USER> games'

 * Byte compiling python modules for python-2.4

However, after emerging executing this works fine:

python /usr/games/lib/pysol/pysol.py


Reproducible: Always
Steps to Reproduce:
1. emerge pysol
2. pysol
3.

Actual Results:  
> \pysol
/usr/bin/pysol: could not find the file 'pysol_24.pyc' !


Expected Results:  

Run pysol 

Portage 2.0.51.22-r2 (default-linux/amd64/2005.1, gcc-3.4.4, glibc-2.3.5-r1,
2.6.11-ck10 x86_64)
=================================================================
System uname: 2.6.11-ck10 x86_64 AMD Opteron(tm) Processor 244
Gentoo Base System version 1.6.13
distcc 2.18.3 x86_64-pc-linux-gnu (protocols 1 and 2) (default port 3632) [disabled]
ccache version 2.4 [enabled]
dev-lang/python:     2.3.5, 2.4.1-r1
sys-apps/sandbox:    1.2.12
sys-devel/autoconf:  2.13, 2.59-r7
sys-devel/automake:  1.4_p6, 1.5, 1.6.3, 1.7.9-r1, 1.8.5-r3, 1.9.6
sys-devel/binutils:  2.16.1
sys-devel/libtool:   1.5.20
virtual/os-headers:  2.6.11-r2
ACCEPT_KEYWORDS="amd64 ~amd64"
AUTOCLEAN="yes"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-Os -march=k8 -fomit-frame-pointer -funit-at-a-time -frename-registers
-mtune=athlon64 -fno-ident -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/kde/2/share/config /usr/kde/3.4/env
/usr/kde/3.4/share/config /usr/kde/3.4/shutdown /usr/kde/3/share/config
/usr/lib/X11/xkb /usr/lib64/mozilla/defaults/pref /usr/share/config
/var/qmail/control"
CONFIG_PROTECT_MASK="/etc/gconf /etc/terminfo /etc/env.d"
CXXFLAGS="-Os -march=k8 -fomit-frame-pointer -funit-at-a-time -frename-registers
-mtune=athlon64 -fno-ident -pipe"
DISTDIR="/usr/portage/distfiles"
FEATURES="autoconfig ccache digest distlocks nodoc noinfo sfperms strict"
GENTOO_MIRRORS="http://gentoo.mirrors.pair.com/
http://mirror.datapipe.net/gentoo http://mirror.datapipe.net/gentoo
http://gentoo.osuosl.org/ http://gentoo.llarian.net/"
LDFLAGS="-Wl,-O1 -Wl,--enable-new-dtags -Wl,--sort-common -Wl,--as-needed -s"
MAKEOPTS="-j4"
PKGDIR="/varsrc/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
PORTDIR_OVERLAY="/usr/local/portage"
SYNC="rsync://rsync.namerica.gentoo.org/gentoo-portage"
USE="amd64 X alsa avi berkdb bitmap-fonts bonobo bzlib cdparanoia cdr chroot
crypt cups curl dedicated dga dillo dio dnd dvd dvdr dvdread eds encode esd faac
faad fam ffmpeg flac foomaticdb fortran freetype gb gd gdbm gif gimp gimpprint
ginac glut gnome gpm gs gstreamer gtk gtk2 gtkhtml imagemagick imlib imlib2
jikes joystick jpeg kde lcd lesstif libdsk lzw lzw-tiff mad maildir matrox mbox
mcal md5sum mikmod mmap mng motif mozilla moznocompose moznoirc moznomail mozp3p
mozsvg mozxmlterm mp3 mpeg mpeg4 mplayer music native ncurses net network nptl
nptlonly offensive ofx ogg openal opengl pam parse-clocks pdf pdflib perl physfs
pic pie png ppds python qt quicktime readline rogue sdl slang sox spell ssl svg
tcltk tcpd theora threads tiff transcode truetype truetype-fonts type1
type1-fonts usb userlocales v4l v4l2 videos vorbis wmf wxwindows xface xft xine
xml xml2 xmms xosd xpm xprint xscreensaver xv xvid xvmc yv12 zlib userland_GNU
kernel_linux elibc_glibc"
Unset:  ASFLAGS, CTARGET, LANG, LC_ALL, LINGUAS




Comment 1


Tupone Alfredo






          2006-03-24 14:18:56 UTC
        

It works fine here









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

