Title: 142448 – current biggles requires libXaw.so.8
URL: https://bugs.gentoo.org/show_bug.cgi?id=142448

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 142448
current biggles requires libXaw.so.8
Last modified: 2006-08-02 04:12:18 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 142448 
      - current biggles requires libXaw.so.8


Summary:
current biggles requires libXaw.so.8
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] Development

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2006-08-01 11:06 UTC by Heitzso





      Modified:
    
2006-08-02 04:12 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Heitzso





          2006-08-01 11:06:05 UTC
        

just did an emerge sync, emerge -ua world
tested my web apps 
a python app now breaks that uses biggles

in /var/www/apache2/error_log I find:
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]   File "/var/www/growthmodels/growthmodels/cgi-bin/popmodel.py", line 7, in ?, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]     , referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] import biggles, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]   File "/usr/lib/python2.4/site-packages/biggles/__init__.py", line 24, in ?, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]     , referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] from biggles import\t\t \\, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]   File "/usr/lib/python2.4/site-packages/biggles/biggles.py", line 27, in ?, referer: http://www.growt
hmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]     , referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] import libplot.renderer, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]   File "/usr/lib/python2.4/site-packages/biggles/libplot/renderer.py", line 22, in ?, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31]     , referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] import libplot, math, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] ImportError, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] : , referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] libXaw.so.8: cannot open shared object file: No such file or directory, referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] , referer: http://www.growthmodels.com/
[Tue Aug 01 13:52:26 2006] [error] [client 192.168.12.31] Premature end of script headers: popmodel.py, referer: http://www.growthmodels.com/

By going into /usr/lib and running

 ln -s libXaw7.so.7 libXaw.so.8

(which I assume is not safe in the long run, but for now ...)
my python/biggles web app works

I assume biggles may not be directly responsible, but rather
one of the secondary libs.  In any case, problem seems to
trigger through biggles and hence filing the bug report here.

I've re-emerged biggles and libXaw and that was not sufficient.

Email me if a full dmesg requested.




Comment 1


Jakub Moc (RETIRED)






          2006-08-01 11:15:23 UTC
        

Run revdep-rebuild or re-emerge xorg-server w/ USE=xprint.




Comment 2


Heitzso





          2006-08-01 12:42:30 UTC
        

revdep-rebuild is not sufficient
(or at least one pass is not sufficient)
I'm trying emerge xorg-server now




Comment 3


Heitzso





          2006-08-02 03:40:46 UTC
        

I ran
emerge xorg-server
with USE=xprint setup in /etc/make.conf
and that was insufficient to create the
necessary libXaw.so.8

a similar gentoo bug report noted that
 emerge -av --unmerge sys-apps/utempter
 emerge -av xterm x11-libs/libXaw
was necessary to fix the same issue for xterm
I'll try that next.






Comment 4


Heitzso





          2006-08-02 04:12:18 UTC
        

what finally fixed was:

emerge -av --unmerge sys-libs/libutempter
emerge -av python-biggles x11-libs/libXaw











Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

