Title: 126605 – Can not build samba-3.0.21b
URL: https://bugs.gentoo.org/show_bug.cgi?id=126605

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 126605
Can not build samba-3.0.21b
Last modified: 2006-03-17 16:27:31 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 126605 
      - Can not build samba-3.0.21b


Summary:
Can not build samba-3.0.21b
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

All
        Other
      







Importance:
      
High
       major
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2006-03-17 15:23 UTC by Thomas T. Veldhouse





      Modified:
    
2006-03-17 16:27 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Thomas T. Veldhouse





          2006-03-17 15:23:09 UTC
        

I started with a 2006.0 stage3 image (apparently i586).  I have built all updates and attempted to emerge samba and get the following.  I have removed ALL references to i586 that I can find on the machine!

---

LIBS="-Wl,-rpath,/usr/lib -lcrypt -lresolv -lnsl -ldl    " \
        python python/setup.py build
running build
running build_py
creating build
creating build/lib.linux-i686-2.4
creating build/lib.linux-i686-2.4/samba
copying python/samba/printerdata.py -> build/lib.linux-i686-2.4/samba
copying python/samba/__init__.py -> build/lib.linux-i686-2.4/samba
running build_ext
building 'spoolss' extension
creating build/temp.linux-i686-2.4
creating build/temp.linux-i686-2.4/python
i586-pc-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -Os -march=athlon -pipe -D_SAMBA_BUILD_ -I/usr/include/mysql -Os -march=i686 -pipe -DHAVE_ERRNO_AS_DEFINE=1 -I/usr/include/libxml2 -fPIC -I/usr/include/python2.4 -c python/py_spoolss.c -o build/temp.linux-i686-2.4/python/py_spoolss.o -Os -march=athlon -pipe -D_SAMBA_BUILD_ -I/usr/include/mysql -Os -march=i686 -pipe -DHAVE_ERRNO_AS_DEFINE=1 -I/usr/include/libxml2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Os -march=athlon -pipe -D_SAMBA_BUILD_ -I/usr/include/mysql -Os -march=i686 -pipe -DHAVE_ERRNO_AS_DEFINE=1 -I/usr/include/libxml2 -Iinclude -I/var/tmp/portage/samba-3.0.21b/work/samba-3.0.21b/source/include -I/var/tmp/portage/samba-3.0.21b/work/samba-3.0.21b/source/ubiqx -I/var/tmp/portage/samba-3.0.21b/work/samba-3.0.21b/source/tdb -I. -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/var/tmp/portage/samba-3.0.21b/work/samba-3.0.21b/source -D_SAMBA_BUILD_
unable to execute i586-pc-linux-gnu-gcc: No such file or directory
error: command 'i586-pc-linux-gnu-gcc' failed with exit status 1
make: *** [python_ext] Error 1

------ INFO ------
Portage 2.0.54 (default-linux/x86/2006.0, gcc-3.4.5, glibc-2.3.5-r2, 2.6.15-gentoo-r1 i686)
=================================================================
System uname: 2.6.15-gentoo-r1 i686 AMD-K7(tm) Processor
Gentoo Base System version 1.6.14
dev-lang/python:     2.4.2
sys-apps/sandbox:    1.2.12
sys-devel/autoconf:  2.13, 2.59-r7
sys-devel/automake:  1.4_p6, 1.5, 1.6.3, 1.7.9-r1, 1.8.5-r3, 1.9.6-r1
sys-devel/binutils:  2.16.1
sys-devel/libtool:   1.5.22
virtual/os-headers:  2.6.11-r2
ACCEPT_KEYWORDS="x86"
AUTOCLEAN="yes"
CBUILD="i686-pc-linux-gnu"
CFLAGS="-Os -march=athlon -pipe"
CHOST="i686-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/kde/2/share/config /usr/kde/3/share/config /usr/share/config /var/bind /var/qmail/control"
CONFIG_PROTECT_MASK="/etc/gconf /etc/terminfo /etc/env.d"
CXXFLAGS="-Os -march=athlon -pipe"
DISTDIR="/usr/portage/distfiles"
FEATURES="autoconfig distlocks sandbox sfperms strict"
GENTOO_MIRRORS="http://gentoo.chem.wisc.edu/gentoo/"
MAKEOPTS=""
PKGDIR="/usr/portage/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
SYNC="rsync://rsync.gentoo.org/gentoo-portage"
USE="x86 3dnow X509 acpi alsa apache2 auth authdaemond authlib bash-completion bcmath berkdb bzip2 clamav clamd cli crypt ctype cups curl curlwrappers dba dvd dvdr dvdread erandom expat fam foomaticdb force-cgi-redirect fortran ftp gd gdbm gif glibc-compat20 gmp hash iconv idea imlib inifile innodb java javascript jpeg jpeg2k libg++ libwww log4j logrotate maildir maildrop memlimit mhash mime mmx mng mono mysql mysqli ncurses neural nls nptl objc objc++ objc-gc odbc oss pam pcre pdflib perl perlsuid php png posix postfix python readline rtc samba sasl session sharedext sharedmem simplexml soap sockets spell spl ssl tcpd tiff tokenizer udev usb vhosts virtual-users xml xml2 xmms xsl zlib userland_GNU kernel_linux elibc_glibc"
Unset:  ASFLAGS, CTARGET, LANG, LC_ALL, LDFLAGS, LINGUAS, PORTDIR_OVERLAY




Comment 1


Thomas T. Veldhouse





          2006-03-17 16:09:58 UTC
        

rebuilding Python fixed the problem.  I am not sure if this is an ebuild issue with Python or an inherant problem with the Python code/configure scripts.  




Comment 2


Jakub Moc (RETIRED)






          2006-03-17 16:27:31 UTC
        

Thanks, closing.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

