Title: 452744 – =dev-python/django-1.4.2: test failures (a lot of them)
URL: https://bugs.gentoo.org/show_bug.cgi?id=452744

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 452744
=dev-python/django-1.4.2: test failures (a lot of them)
Last modified: 2015-02-28 14:01:29 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 452744 
      - =dev-python/django-1.4.2: test failures (a lot of them)


Summary:
=dev-python/django-1.4.2: test failures (a lot of them)
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:
utf8  
  


Keywords:








Depends on:







Blocks:









 





      Reported:
    
2013-01-17 22:39 UTC by Michał Górny





      Modified:
    
2015-02-28 14:01 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    




Build log for py2.7

              (build-python2.7.log,254.49 KB,
                text/plain)

            
2013-01-17 22:39 UTC,

            Michał Górny




Details





Build log for py2.6

              (build-python2.6.log,249.47 KB,
                text/plain)

            
2013-01-17 22:39 UTC,

            Michał Górny




Details





Build log for py2.5

              (build-python2.5.log,230.75 KB,
                text/plain)

            
2013-01-17 22:39 UTC,

            Michał Górny




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Michał Górny









          2013-01-17 22:39:16 UTC
        

Created attachment 335962 [details]
Build log for py2.7

I guess LC_ALL=C would be partially responsible. Some of them may be my fault too. I'm too tired to look at them but feel free to take a closer look at the logs I'm attaching.




Comment 1


Michał Górny









          2013-01-17 22:39:31 UTC
        

Created attachment 335964 [details]
Build log for py2.6




Comment 2


Michał Górny









          2013-01-17 22:39:44 UTC
        

Created attachment 335966 [details]
Build log for py2.5




Comment 3


Justin Lecher (RETIRED)






          2015-02-28 14:01:29 UTC
        

Recent versions work fine here. PLease reopen if still exists.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

