Title: 188908 – app-pda/libopensync-0.22: econf fails for python include path
URL: https://bugs.gentoo.org/show_bug.cgi?id=188908

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 188908
app-pda/libopensync-0.22: econf fails for python include path
Last modified: 2007-08-15 13:02:44 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 188908 
      - app-pda/libopensync-0.22: econf fails for python include path


Summary:
app-pda/libopensync-0.22: econf fails for python include path
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

AMD64
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2007-08-14 20:50 UTC by Keno





      Modified:
    
2007-08-15 13:02 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    




emerge --info is attached

              (text,10.98 KB,
                text/plain)

            
2007-08-14 20:53 UTC,

            Keno




Details





Sorry. Here is attached the config.log

              (config.log,39.85 KB,
                text/plain)

            
2007-08-14 22:02 UTC,

            Keno




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Keno





          2007-08-14 20:50:09 UTC
        

econf fails when app-pda/libopensync-0.22 was tried to emerge.
The output is below.

Reproducible: Always

Actual Results:  
checking for SWIG version... 1.3.31
configure: SWIG executable is '/usr/bin/swig'
configure: SWIG library directory is '/usr/share/swig/1.3.31'
checking for Python include path... find: `/usr/local/include/python2.4/': No such file or directory
find: `/usr/local/include/python/': No such file or directory

configure: error: cannot find Python include path

!!! Please attach the following file when filing a report to bugs.gentoo.org:
!!! /var/tmp/portage/app-pda/libopensync-0.22/work/libopensync-0.22/config.log

!!! ERROR: app-pda/libopensync-0.22 failed.
Call stack:
  ebuild.sh, line 1632:   Called dyn_compile
  ebuild.sh, line 983:   Called qa_call 'src_compile'
  ebuild.sh, line 44:   Called src_compile
  libopensync-0.22.ebuild, line 41:   Called econf '--enable-engine' '--enable-tools' '--enable-python' '--disable-debug' '--disable-tracing'
  ebuild.sh, line 586:   Called die

!!! econf failed
!!! If you need support, post the topmost build error, and the call stack if relevant.




Comment 1


Keno





          2007-08-14 20:53:29 UTC
        

Created attachment 128103 [details]
emerge --info is attached




Comment 2


Jakub Moc (RETIRED)






          2007-08-14 21:01:17 UTC
        

(In reply to comment #0)
> !!! Please attach the following file when filing a report to bugs.gentoo.org:
> !!! /var/tmp/portage/app-pda/libopensync-0.22/work/libopensync-0.22/config.log

Do it, please.




Comment 3


Keno





          2007-08-14 22:02:08 UTC
        

Created attachment 128107 [details]
Sorry. Here is attached the config.log




Comment 4


Keno





          2007-08-14 22:11:44 UTC
        

The problem might be that I have had to make a symlink /usr/local/bin/python to the original /usr/bin/python for other (non-gentoo) apps. The includes are, of course, in /usr/include/python2.4 not in /usr/local... But I need for this link. May I create one for includes?






Comment 5


Jakub Moc (RETIRED)






          2007-08-14 22:13:29 UTC
        

Please, don't do such things. There's no need to symlink stuff that's in $PATH already.





Comment 6


Keno





          2007-08-15 10:32:43 UTC
        

Removing this python link the package emerges. (So now I can put back this link for my other stupid stuff. :-)





Comment 7


Keno





          2007-08-15 13:02:44 UTC
        

I have found that stupid staff that does not work without the link. That is the java-config-2 script which contains #!/usr/local/bin/python in its first line.(java-config-1 begins with #!/usr/bin/python) Of course, this script works fine with the problematic link.
This script belongs to dev-java/java-config-1.3.7. (So it is in a Gentoo package.)
Should this issue be forwarded to java staff?










Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

