Title: 178364 – dev-python/pyx-0.9 does not find LaTeX fonts / Wrong paths in configuration
URL: https://bugs.gentoo.org/show_bug.cgi?id=178364

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 178364
dev-python/pyx-0.9 does not find LaTeX fonts / Wrong paths in configuration
Last modified: 2008-01-03 20:05:10 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 178364 
      - dev-python/pyx-0.9 does not find LaTeX fonts / Wrong paths in configuration


Summary:
dev-python/pyx-0.9 does not find LaTeX fonts / Wrong paths in configuration
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       major
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2007-05-13 16:09 UTC by Florian Nöding





      Modified:
    
2008-01-03 20:05 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



djc









See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Florian Nöding





          2007-05-13 16:09:52 UTC
        

PyX can not find LaTeX fonts because it's configuration file is containing wrong paths (probably more issues):
Config file: /usr/lib/python2.5/site-packages/pyx/siteconfig.py
Content:
lfsdir = '/var/tmp/portage/pyx-0.9/image/usr/share/pyx'
sharedir = '/var/tmp/portage/pyx-0.9/image/usr/share/pyx'
pyxrcdir = '/var/tmp/portage/pyx-0.9/image/etc'

But it should be:
lfsdir = '/usr/share/pyx'
sharedir = '/usr/share/pyx'
pyxrcdir = '/etc'

Reproducible: Always

Steps to Reproduce:
Just emerge dev-python/pyx-0.9. Then check /usr/lib/python2.5/site-packages/pyx/siteconfig.py




Comment 1


Dirkjan Ochtman (RETIRED)






          2007-10-12 10:28:45 UTC
        

WORKSFORME with the current ebuild in the tree.




Comment 2


Ali Polatel (RETIRED)






          2008-01-03 20:05:10 UTC
        

pyx-0.10 works fine here:
qlist pyx | xargs grep lfsdir
site-packages/pyx/siteconfig.py:lfsdir = "/usr/share/pyx"
Closing this one, please reopen if the problem is still not fixed.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

